name: Publish

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed
    branches:
      - refs/heads/main
    paths:
      - ".changeset/**"
      - "package.json"
      - "**/package.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Create PR & Publish
        uses: changesets/action@v1
        with:
          publish: pnpm ci:publish
          version: pnpm changeset version
          commit: "ci: publish new versions"
          title: "ci: publish new versions"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}