name: Release

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create release PR & Publish
        uses: changesets/action@v1
        with:
          publish: pnpm dlx changeset publish --tag alpha
          version: pnpm dlx changeset version
          commit: "ci: release new versions"
          title: "ci: release new versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}